TOPLEVEL_LANG = verilog
VERILOG_SOURCES = /home/nivetha608/cocotb-coverage/RISC-V-Vector-Processor/hw/vector_logic.v
TOPLEVEL = logic_256bit
MODULE = test_logic_256bit

SIM = icarus

include $(shell cocotb-config --makefiles)/Makefile.sim
